require 'rgeo'
require 'mongoid'
require 'active_support/core_ext/string/inflections'
require 'active_support/concern'
require 'mongoid_spatial/contexts/mongo'
require 'mongoid_spatial/criteria'
require 'mongoid_spatial/criterion'
require 'mongoid_spatial/extentions/hash/criteria_helpers'
require 'mongoid_spatial/extentions/symbol/inflections'
require 'mongoid_spatial/field_option'
require 'mongoid_spatial/fields/point'
require 'mongoid_spatial/fields/polygon'
require 'mongoid_spatial/fields/line_string'
require 'mongoid_spatial/finders'
require 'mongoid_spatial/spatial'
require 'mongoid_spatial/geospatial'

