require 'rgeo'
require 'mongoid'
require 'active_support/core_ext/string/inflections'
require 'active_support/concern'
require 'mongoid_geospatial/contexts/mongo'
require 'mongoid_geospatial/criteria'
require 'mongoid_geospatial/criterion'
require 'mongoid_geospatial/extensions/hash'
require 'mongoid_geospatial/extensions/symbol'
require 'mongoid_geospatial/field_option'
require 'mongoid_geospatial/fields/point'
require 'mongoid_geospatial/fields/polygon'
require 'mongoid_geospatial/fields/line_string'
require 'mongoid_geospatial/finders'
require 'mongoid_geospatial/geospatial'

